trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDirectory: 'build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Build the App'

- script: |
    npm test
  displayName: 'Run Tests'

# Optionally archive artifacts (build output)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(buildDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
